[package]
name = "html2pdf"
version = "0.1.0"
edition = "2018"
authors = ["Igor Laborie <igor@monkeypatch.io>"]
description = "Convert HTML to PDF using a Headless Chrome browser"
license = "Apache-2.0 OR MIT"

[dependencies]

headless_chrome = "0.9"

structopt = "0.3"

log = "0.4"
pretty_env_logger = "0.4"
